server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: cafetaria
          uri: lb://cafetaria
          predicates:
            - Path=/notes/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
